# Generated by Django 5.1.2 on 2025-02-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='combi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
