# Generated by Django 5.1.2 on 2025-02-10 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('resultado', models.PositiveIntegerField()),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('loteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.loteria')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de Lotería',
                'verbose_name_plural': 'Resultados de Loterías',
                'unique_together': {('loteria', 'fecha')},
            },
        ),
    ]
