# Generated by Django 5.1.2 on 2024-11-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='nombre',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
