# Generated by Django 5.1.2 on 2025-01-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_venta_combi'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='combi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
