# Generated by Django 5.1.2 on 2024-11-11 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dia_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='fechaventa',
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero',
            field=models.CharField(max_length=20),
        ),
    ]
