# Generated by Django 5.1.2 on 2025-05-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
