# Generated by Django 5.1.2 on 2024-11-11 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_venta_fechaventa_venta_fecha_venta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='loterias',
        ),
        migrations.AddField(
            model_name='venta',
            name='loteria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.loteria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero',
            field=models.CharField(max_length=100),
        ),
    ]
