# Generated by Django 5.1.2 on 2024-11-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_venta_loterias_venta_loteria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='loteria',
        ),
        migrations.AddField(
            model_name='venta',
            name='loterias',
            field=models.ManyToManyField(to='core.loteria'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero',
            field=models.CharField(max_length=20),
        ),
    ]
