# Generated by Django 5.1.2 on 2025-08-21 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loteria_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=10)),
                ('valor', models.PositiveIntegerField()),
                ('cifras', models.PositiveSmallIntegerField()),
                ('premio', models.PositiveBigIntegerField()),
                ('fecha', models.DateField(db_index=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('loteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premios', to='core.loteria')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premios', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='core.venta')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('venta', 'loteria', 'fecha'), name='uniq_premio_por_venta_loteria_fecha')],
            },
        ),
    ]
