# Generated by Codex on 2026-02-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_premio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VentaAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[
                    ("sale.create_attempt", "Sale Create Attempt"),
                    ("sale.create_success", "Sale Create Success"),
                    ("sale.create_rejected", "Sale Create Rejected"),
                    ("sale.create_rejected_closed_lottery", "Sale Create Rejected Closed Lottery"),
                    ("sale.update_blocked", "Sale Update Blocked"),
                    ("sale.delete_blocked", "Sale Delete Blocked"),
                    ("sale.lotteries_change_blocked", "Sale Lotteries Change Blocked"),
                ], db_index=True, max_length=64)),
                ("status", models.CharField(choices=[
                    ("info", "Info"),
                    ("success", "Success"),
                    ("rejected", "Rejected"),
                    ("blocked", "Blocked"),
                    ("error", "Error"),
                ], db_index=True, max_length=16)),
                ("message", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="venta_audit_logs", to=settings.AUTH_USER_MODEL)),
                ("venta", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_logs", to="core.venta")),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "verbose_name": "Log de auditoria de venta",
                "verbose_name_plural": "Logs de auditoria de ventas",
            },
        ),
    ]
