# Generated by Django 5.1.2 on 2024-11-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteria',
            name='ventas_seleccionadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero',
            field=models.CharField(max_length=50),
        ),
    ]
