# Generated by Django 5.1.2 on 2026-03-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ventaauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(default='global', editable=False, max_length=20, unique=True)),
                ('limite_apuesta_por_numero', models.PositiveIntegerField(default=0, help_text='Tope por numero y loteria para un dia. 0 desactiva el limite.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion de venta',
                'verbose_name_plural': 'Configuracion de ventas',
            },
        ),
    ]
