# Generated by Django 5.1.2 on 2026-03-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuracionventa_alter_ventaauditlog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaauditlog',
            name='event_type',
            field=models.CharField(choices=[('sale.create_attempt', 'Sale Create Attempt'), ('sale.create_success', 'Sale Create Success'), ('sale.create_rejected', 'Sale Create Rejected'), ('sale.create_rejected_closed_lottery', 'Sale Create Rejected Closed Lottery'), ('sale.update_allowed', 'Sale Update Allowed'), ('sale.update_blocked', 'Sale Update Blocked'), ('sale.delete_blocked', 'Sale Delete Blocked'), ('sale.lotteries_change_allowed', 'Sale Lotteries Change Allowed'), ('sale.lotteries_change_blocked', 'Sale Lotteries Change Blocked')], db_index=True, max_length=64),
        ),
    ]
