# Generated by Django 5.1.2 on 2024-11-19 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_loteria_ventas_seleccionadas_alter_venta_monto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loteria',
            name='ventas_seleccionadas',
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
