# Generated by Django 5.1.2 on 2026-03-10 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_ventaauditlog_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaDescargue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('numero', models.CharField(db_index=True, max_length=50)),
                ('monto', models.PositiveIntegerField()),
                ('descargue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_descargue', to=settings.AUTH_USER_MODEL)),
                ('loteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_descargue', to='core.loteria')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_descargue_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta de descargue',
                'verbose_name_plural': 'Ventas de descargues',
                'ordering': ('-fecha_venta', '-id'),
            },
        ),
    ]
