# Generated by Django 5.1.2 on 2026-03-10 01:58

from django.db import migrations


def crear_grupo_descargue(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="descargue")


def eliminar_grupo_descargue(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="descargue").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ventadescargue'),
    ]

    operations = [
        migrations.RunPython(crear_grupo_descargue, eliminar_grupo_descargue),
    ]
