# Generated by Django 5.1.2 on 2024-11-27 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='telefono',
            field=models.CharField(default=3002393652, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Ingrese un número de teléfono válido (10 dígitos).')]),
            preserve_default=False,
        ),
    ]
