# Generated by Django 5.1.2 on 2024-11-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_venta_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='telefono',
        ),
    ]
