# Generated by Codex on 2026-03-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_create_descargue_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='venta_descargue',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='premios',
                to='core.ventadescargue',
            ),
        ),
        migrations.AddConstraint(
            model_name='premio',
            constraint=models.UniqueConstraint(
                fields=('venta_descargue', 'loteria', 'fecha'),
                name='uniq_premio_por_descargue_loteria_fecha',
            ),
        ),
        migrations.AddConstraint(
            model_name='premio',
            constraint=models.CheckConstraint(
                condition=(
                    (
                        models.Q(venta__isnull=False, venta_descargue__isnull=True)
                    )
                    | (
                        models.Q(venta__isnull=True, venta_descargue__isnull=False)
                    )
                ),
                name='premio_con_una_sola_fuente',
            ),
        ),
    ]
