# Generated by Django 5.1.2 on 2026-04-18 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_premio_es_combinado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='premio',
            index=models.Index(fields=['vendedor'], name='premio_vendedor_idx'),
        ),
        migrations.AddIndex(
            model_name='premio',
            index=models.Index(fields=['vendedor', 'fecha'], name='premio_vendedor_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['vendedor'], name='venta_vendedor_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['vendedor', 'fecha_venta'], name='venta_vendedor_fecha_idx'),
        ),
    ]
