# Generated by Django 5.1.2 on 2026-04-18 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('exito', 'Éxito'), ('alerta', 'Alerta'), ('error', 'Error')], default='info', max_length=10)),
                ('leida', models.BooleanField(db_index=True, default=False)),
                ('url', models.CharField(blank=True, help_text='URL opcional para redirigir al hacer click', max_length=300)),
                ('creada_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ('-creada_en',),
            },
        ),
    ]
