# Generated by Django 5.1.2 on 2026-04-30 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_notificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonado',
                'verbose_name_plural': 'Abonados',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='AbonadoApuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('total', models.PositiveBigIntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('abonado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas', to='core.abonado')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apuestas_abonados', to=settings.AUTH_USER_MODEL)),
                ('ventas', models.ManyToManyField(blank=True, related_name='apuestas_abonado', to='core.venta')),
            ],
            options={
                'verbose_name': 'Apuesta de abonado',
                'verbose_name_plural': 'Apuestas de abonados',
                'ordering': ('-fecha', '-id'),
            },
        ),
        migrations.CreateModel(
            name='JugadaAbonado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=4)),
                ('monto', models.PositiveIntegerField()),
                ('es_combinado', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('abonado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadas', to='core.abonado')),
            ],
            options={
                'verbose_name': 'Jugada de abonado',
                'verbose_name_plural': 'Jugadas de abonado',
                'ordering': ('orden', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='abonado',
            index=models.Index(fields=['vendedor', 'activo'], name='abonado_vendedor_activo_idx'),
        ),
        migrations.AddConstraint(
            model_name='abonado',
            constraint=models.UniqueConstraint(fields=('vendedor', 'nombre'), name='uniq_abonado_por_vendedor_nombre'),
        ),
        migrations.AddIndex(
            model_name='abonadoapuesta',
            index=models.Index(fields=['abonado', 'fecha'], name='abonado_apuesta_fecha_idx'),
        ),
    ]
