# Generated by Django 5.1.2 on 2026-05-03 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_abonado_abonadoapuesta_jugadaabonado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('action', models.CharField(choices=[('resultado.create', 'Creado'), ('resultado.update', 'Modificado'), ('resultado.delete', 'Eliminado')], db_index=True, max_length=32)),
                ('valor_anterior', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_nuevo', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultado_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('loteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultado_audit_logs', to='core.loteria')),
                ('resultado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.resultado')),
            ],
            options={
                'verbose_name': 'Log de auditoría de resultado',
                'verbose_name_plural': 'Logs de auditoría de resultados',
                'ordering': ('-created_at',),
            },
        ),
    ]
