# Generated by Django 5.1.2 on 2026-05-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_dia_festivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonado',
            name='dias',
            field=models.ManyToManyField(blank=True, related_name='abonados_activos', to='core.dia', verbose_name='Días activos'),
        ),
    ]
