name: Importar resultados automáticamente

on:
  schedule:
    - cron: '30 5 * * *'  # Ejecuta a las 12:30 AM Colombia todos los días
  workflow_dispatch:  # Permite ejecución manual desde GitHub

jobs:
  importar_resultados:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar comando de importación
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          python manage.py importar_resultados_diarios
